# Generated by Django 4.2.5 on 2023-09-29 07:50

from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('isdefault', models.BooleanField(null=True)),
                ('datecreate', models.DateTimeField()),
                ('dateupdate', models.DateTimeField()),
                ('datedeleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('datecreate', models.DateTimeField()),
                ('dateupdate', models.DateTimeField(null=True)),
                ('datedeleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=80, null=True)),
                ('order_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('In Cart', 'In Cart'), ('Placed', 'Placed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], max_length=20)),
                ('datecreate', models.DateTimeField()),
                ('dateupdate', models.DateTimeField(null=True)),
                ('datedeleted', models.DateTimeField(null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mysite.address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock_count', models.DecimalField(decimal_places=2, max_digits=20)),
                ('createdby', models.IntegerField()),
                ('updateby', models.IntegerField(null=True)),
                ('deletedby', models.IntegerField(null=True)),
                ('datecreated', models.DateTimeField()),
                ('dateupdated', models.DateTimeField(null=True)),
                ('datedeleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('datecreate', models.DateTimeField()),
                ('dateupdate', models.DateTimeField(null=True)),
                ('datedeleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, unique=True, validators=[mysite.models.User.is_valid_email])),
                ('phone_no', models.CharField(max_length=50, unique=True, validators=[mysite.models.User.is_valid_phone_number])),
                ('hashed_password', models.CharField(max_length=500)),
                ('datecreate', models.DateTimeField()),
                ('dateuupdate', models.DateTimeField(null=True)),
                ('datedeleted', models.DateTimeField(null=True)),
                ('salt', models.CharField(max_length=500)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.roles')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.country')),
            ],
        ),
        migrations.CreateModel(
            name='Productcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreate', models.DateTimeField()),
                ('dateupdate', models.DateTimeField(null=True)),
                ('datedeleted', models.DateTimeField()),
                ('createdby', models.IntegerField(null=True)),
                ('updatedby', models.IntegerField(null=True)),
                ('deletedby', models.IntegerField(null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.country')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.user')),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('datecreate', models.DateTimeField()),
                ('dateupdate', models.DateTimeField(blank=True, null=True)),
                ('datedeleted', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.user'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.product')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.city'),
        ),
        migrations.AddField(
            model_name='address',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.country'),
        ),
        migrations.AddField(
            model_name='address',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.state'),
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.user'),
        ),
    ]
