# Generated by Django 4.2.5 on 2023-10-02 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateuupdate',
            new_name='dateupdate',
        ),
        migrations.RemoveField(
            model_name='city',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='city',
            name='product_id',
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='mysite.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='dateupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
