# Generated by Django 4.2.5 on 2023-10-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_dateuupdate_user_dateupdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='mysite.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='mysite.product'),
            preserve_default=False,
        ),
    ]
