# Generated by Django 4.2.5 on 2023-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_productcategory_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='createdby',
            field=models.IntegerField(null=True),
        ),
    ]
