# Generated by Django 4.2.5 on 2023-10-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_productcategory_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='createdby',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
