# Generated by Django 4.2.5 on 2023-10-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_rename_roles_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Roles',
        ),
    ]
