# Generated by Django 4.2.5 on 2023-10-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_rename_role_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='createdby',
            field=models.IntegerField(null=True),
        ),
    ]
