# Generated by Django 4.2.5 on 2023-10-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_rename_roles_role_alter_productcategory_createdby'),
    ]


    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='createdby',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
