# Generated by Django 4.2.5 on 2023-10-03 05:48

from django.db import migrations, models
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_productcategory_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=50, validators=[mysite.models.User.is_valid_phone_number]),
        ),
    ]
