# Generated by Django 4.2.5 on 2023-10-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_alter_user_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
    ]
