# Generated by Django 4.2.5 on 2023-10-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_rename_role_id_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_id',
            new_name='product',
        ),
    ]
