# Generated by Django 4.2.5 on 2023-10-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_user_last_login_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hashed_password',
        ),
    ]
