# Generated by Django 4.2.5 on 2023-10-10 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_alter_user_datedeleted_alter_user_dateupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datedeleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateupdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deletedby',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='updateby',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
