# Generated by Django 4.2.5 on 2023-10-11 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_alter_product_datedeleted_alter_product_dateupdated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='datedeleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='dateupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='datedeleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='dateupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='datecreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='datedeleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='dateupdate',
            field=models.DateTimeField(null=True),
        ),
    ]
