# Generated by Django 4.2.5 on 2023-10-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_city_datecreate_city_datedeleted_city_dateupdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
    ]
